import test from 'node:test';
import assert from 'node:assert/strict';
import Stripe from 'stripe';
import {createSafety,categories,fields,acknowledgmentVersion,validateUpload} from '../core.mjs';
import {httpServer} from '../server.mjs';
const sdk=new Stripe('rk_test_fixture_only');
function fixture(){
 let time=Date.now();const sent=[],objects=new Map();
 const session={id:'cs_test_safety',mode:'payment',status:'complete',payment_status:'paid',livemode:false,payment_link:'plink_safety',amount_total:49900,amount_subtotal:49900,currency:'usd',payment_intent:'pi_safety',customer_details:{email:'client@example.test'}};
 const charge={paid:true,refunded:false,amount_refunded:0,disputed:false};
 const stripe={webhooks:sdk.webhooks,checkout:{sessions:{retrieve:async()=>session,listLineItems:async()=>({data:[{price:{id:'price_safety'},quantity:1}],has_more:false})}},paymentIntents:{retrieve:async()=>({status:'succeeded',amount_received:49900,currency:'usd',livemode:false,latest_charge:charge})}};
 let user='';const supabase={auth:{getUser:async jwt=>{user=jwt;return {data:{user:jwt==='invalid'?null:{id:jwt}}};}},from:()=>{const query={select:()=>query,eq:()=>query,maybeSingle:async()=>({data:user==='owner'?{user_id:'owner',role:'owner'}:null})};return query;},storage:{from:bucket=>({download:async path=>({data:new Blob([objects.get(bucket+'/'+path)||'private document'])}),upload:async(path,bytes)=>{objects.set(bucket+'/'+path,bytes);return {error:null};}})}};
 const config={dbPath:':memory:',siteOrigin:'https://example.test',live:false,paymentLinkId:'plink_safety',priceId:'price_safety',webhookSecret:'whsec_fixture_only'};
 const service=createSafety({config,supabase,stripe,sendEmail:async m=>sent.push(m),now:()=>time});
 const raw=()=>JSON.stringify({id:'evt_test',type:'checkout.session.completed',livemode:false,data:{object:{id:session.id}}});
 const pay=()=>{const body=raw();return service.webhook(Buffer.from(body),sdk.webhooks.generateTestHeaderString({payload:body,secret:config.webhookSecret}));};
 const token=()=>sent.at(-1).text.match(/#access=([A-Za-z0-9_-]+)/)[1];
 const intake=()=>({...Object.fromEntries(fields.map(([key])=>[key,'Response'])),acknowledged:true,acknowledgmentVersion});
 return {service,session,charge,sent,objects,pay,token,intake,advance:n=>{time+=n;}};
}
test('logged out and ordinary accounts cannot access operations or direct documents',async()=>{const f=fixture();for(const path of ['/staff/library','/staff/library/01','/staff/engagements']){await assert.rejects(f.service.route('GET',path,''),e=>e.status===401);await assert.rejects(f.service.route('GET',path,'student'),e=>e.status===403);}f.service.db.close();});
test('approved owner can access all nine ordered documents and private ZIP',async()=>{const f=fixture();const r=await f.service.route('GET','/staff/library','owner');assert.equal(r.items.length,10);assert.equal(r.items[0].title,'Client Delivery Playbook');assert.equal(r.items[8].title,'Internal Engagement Worksheet');const file=await f.service.route('GET','/staff/library/complete','owner');assert.equal(file.mime,'application/zip');assert(file.bytes.length);f.service.db.close();});
test('paid client can acknowledge and submit privately; uploads require acknowledgment and permitted types',async()=>{const f=fixture();await f.pay();await f.service.queue();const token=f.token();await assert.rejects(f.service.route('POST','/client/uploads',token,{}),e=>e.status===409);await assert.rejects(f.service.route('POST','/client/intake',token,{...f.intake(),acknowledged:false}),e=>e.status===400);await f.service.route('POST','/client/intake',token,f.intake());await f.service.route('POST','/client/uploads',token,{name:'plan.pdf',base64:Buffer.from('%PDF-fixture').toString('base64'),category:categories[0],redacted:true});assert.equal(f.objects.size,1);assert([...f.objects.keys()][0].startsWith('safety-client-uploads/'));await assert.rejects(f.service.route('GET','/staff/library',token),e=>e.status===403);f.service.db.close();});
test('forged webhook, unpaid payment, wrong product, and fake client flags cannot unlock',async()=>{const f=fixture();await assert.rejects(f.service.webhook(Buffer.from('{}'),'bad'),e=>e.status===400);f.session.payment_status='unpaid';await f.pay();await f.service.queue();assert.equal(f.sent.length,0);f.session.payment_status='paid';f.session.payment_link='other';await f.pay();await f.service.queue();assert.equal(f.sent.length,0);await assert.rejects(f.service.route('GET','/client','paid=true'),e=>e.status===401);f.service.db.close();});
test('duplicate events produce one invitation; revoked/refunded payment and expired tokens denied',async()=>{const f=fixture();await f.pay();await f.pay();await f.service.queue();await f.service.queue();assert.equal(f.sent.length,1);const token=f.token();f.charge.refunded=true;await assert.rejects(f.service.client(token),e=>e.status===403);f.charge.refunded=false;f.advance(8*86400000);await assert.rejects(f.service.client(token),e=>e.status===401);f.service.db.close();});
test('only staff can change statuses; changing report status sends no report',async()=>{const f=fixture();await f.pay();await f.service.queue();const e=await f.service.client(f.token());await assert.rejects(f.service.route('PATCH','/staff/engagements/'+e.id,'student',{status:'Closed'}),e=>e.status===403);await f.service.route('PATCH','/staff/engagements/'+e.id,'owner',{status:'Report ready'});assert.equal(f.sent.length,1);assert.equal(f.service.db.prepare('SELECT COUNT(*) n FROM audit').get().n,1);f.service.db.close();});
test('rejects executable, fake PDF/DOCX, path traversal, disallowed category and oversized upload',()=>{for(const input of [{name:'x.exe'},{name:'../x.pdf'},{name:'x.pdf',base64:Buffer.from('<html>').toString('base64')},{name:'x.docx'},{category:'Credentials'},{redacted:false},{base64:'A'.repeat(14000004)}])assert.throws(()=>validateUpload({name:'plan.pdf',base64:Buffer.from('%PDF-test').toString('base64'),category:categories[0],redacted:true,...input}));});
test('HTTP rejects public file requests, fake session flags, unauthenticated library; strict no-store',async()=>{const f=fixture(),server=httpServer(f.service,'https://example.test');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{for(const [path,status] of [['/staff/library/01',401],['/01.docx',404],['/client?paid=true',401]]){const r=await fetch(base+path);assert.equal(r.status,status);assert.equal(r.headers.get('cache-control'),'no-store');}const r=await fetch(base+'/staff/library',{headers:{Authorization:'Bearer student'}});assert.equal(r.status,403);}finally{await new Promise(r=>server.close(r));f.service.db.close();}});
